name: firebase_counter
description: Firebase counter app
version: 0.0.1
environment:
  sdk: '>=1.20.0 <2.0.0'
dependencies:
  angular2:
  angular2_components: ^0.3.1-alpha
  firebase: '^3.0.0'
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
